# Generated by Django 3.0.5 on 2020-04-27 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_login_post_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
